/**
 * Generates `src/components/icons.generated.ts`.
 *
 * The icons are Material Symbols (outlined, weight 400) — Google's own set,
 * taken from `@material-symbols/svg-400` and inlined as path data so the app
 * ships no icon font and makes no network request.
 *
 * docs/02 §4 found the original's UI is 531 custom layouts whose Android
 * drawables are not reusable, so the icon set had to be new regardless; using
 * the Material set rather than drawing glyphs is what makes the result look
 * like a Material app instead of an approximation of one.
 *
 * Add a name here, run `bun run gen:icons`, then use `<Icon name="…" />`.
 */

import { readFileSync, writeFileSync } from "node:fs";

/** Material Symbols names, grouped by where they are used. */
const ICONS = [
  // Tools (Toolbar).
  "stylus", "ink_eraser", "crop_free", "lasso_select", "text_fields",
  "sticky_note_2", "shapes", "table", "image", "bar_chart", "ads_click",
  "pan_tool",

  // Navigation and chrome.
  "arrow_back", "close", "more_vert", "check", "add", "remove", "search",
  "settings", "sort", "menu", "keyboard_arrow_left", "keyboard_arrow_right",
  "keyboard_arrow_down", "refresh",

  // Editing.
  "undo", "redo", "save", "content_copy", "delete", "delete_forever",
  "restore_from_trash", "edit", "layers", "visibility", "visibility_off",
  "lock", "lock_open", "arrow_upward", "arrow_downward", "zoom_in", "zoom_out",
  "fit_screen", "note_stack", "drag_indicator",

  // Library.
  "folder", "create_new_folder", "sell", "new_label", "note_add", "file_open",
  "picture_as_pdf", "download", "description",

  // Sync and account.
  "cloud_sync", "cloud_off", "login", "logout", "person",

  // Classroom.
  "school", "co_present", "front_hand", "lock_clock", "monitoring", "campaign",
  "add_circle",

  // Inspector: text alignment and shapes.
  "format_align_left", "format_align_center", "format_align_right",
  "rectangle", "rounded_corner", "circle", "change_history", "diamond",
  "horizontal_rule", "north_east",

  // Status.
  "error", "warning", "info", "check_circle", "cloud_done", "pending",
] as const;

const SRC = "../node_modules/@material-symbols/svg-400/outlined";

const entries = ICONS.map((name) => {
  const svg = readFileSync(new URL(`${SRC}/${name}.svg`, import.meta.url), "utf8");

  // Material Symbols are single-colour outlines: one or more <path d>, nothing
  // else. Anything else would silently lose detail, so refuse it.
  const stripped = svg
    .replace(/<svg[^>]*>|<\/svg>/g, "")
    .replace(/<path d="[^"]*"\s*\/>/g, "")
    .trim();
  if (stripped !== "") throw new Error(`${name}.svg contains unsupported markup: ${stripped}`);

  const d = [...svg.matchAll(/<path d="([^"]*)"/g)].map((m) => m[1]).join(" ");
  if (!d) throw new Error(`${name}.svg has no path data`);

  return `  "${name}": "${d}",`;
}).join("\n");

const out = `/*
 * Material Symbols path data.
 *
 * GENERATED by \`scripts/gen-icons.ts\` — run \`bun run gen:icons\` after
 * editing that file's icon list. Do not edit by hand.
 *
 * Every path is drawn on Material's 960×960 grid with the origin at the
 * top-left of a \`0 -960 960 960\` viewBox, which is why <Icon> hard-codes that
 * viewBox rather than deriving one.
 */

export const ICON_PATHS = {
${entries}
} as const;

export type IconName = keyof typeof ICON_PATHS;
`;

writeFileSync(new URL("../src/components/icons.generated.ts", import.meta.url), out);
console.log(`${ICONS.length} icons written`);
